global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['backend:2112']
  - job_name: "node"
    static_configs:
      - targets: [ "node-exporter:9100" ]
